import { IProjectsData } from '../types/interfaces';

export const projects: IProjectsData[] = [
  {
    image: '/public/images/test.png',
    name: 'Insights',
    about: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint dignissimos eaque deserunt libero cum perferendis assumenda ab repellat dolorem voluptas, eius, iusto perspiciatis consequuntur. Minima nulla voluptas quis ea ipsa!
    Autem, labore earum aspernatur in numquam neque illum libero, maxime, sed nam minus odit vitae doloremque! In id quidem rem, beatae optio ipsa eligendi eius quod assumenda exceptu`,
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '../../public/images/test.png',
    name: 'Times',
    about: 'About Times',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '/public/images/test.png',
    name: 'E-wallet',
    about: 'About Ewallet',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '/public/images/test.png',
    name: 'Times',
    about: 'About test',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '/public/images/test.png',
    name: 'Times',
    about: 'About test',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
];
