import { IProjectsData } from '../types/interfaces';
export const projects: IProjectsData[] = [
  {
    image: '../../public/images/test.png',
    name: 'Insights',
    about: 'About Insights',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '../../public/images/test.png',
    name: 'Times',
    about: 'About Times',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '../../public/images/test.png',
    name: 'E-wallet',
    about: 'About Ewallet',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '../../public/images/test.png',
    name: 'Times',
    about: 'About test',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
  {
    image: '../../public/images/test.png',
    name: 'Times',
    about: 'About test',
    description: 'Description test',
    tags: [
      'TypeScript',
      'React',
      'Redux',
      'Redux Saga',
      'Emotion.js',
      'ChakraUI',
      'date-fns',
    ],
  },
];
